# Generated by Django 6.0.3 on 2026-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified_user_real_name_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', '跟随系统'), ('dark', '深色'), ('light', '浅色')], default='system', max_length=10, verbose_name='主题偏好'),
        ),
    ]
