# Generated by Django 6.0.3 on 2026-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=20, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '下架'), ('ban', '禁言')], max_length=20, verbose_name='操作')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词')),
                ('level', models.CharField(choices=[('hard', '硬拦截'), ('soft', '软标记')], default='soft', max_length=10, verbose_name='级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'sensitive_words',
            },
        ),
    ]
