# Generated by Django 6.0.3 on 2026-03-27 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_favorite_report'),
        ('posts', '0005_postimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='是否已拉黑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='楼主')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_conversations', to=settings.AUTH_USER_MODEL, verbose_name='发起方')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='posts.post', verbose_name='关联帖子')),
            ],
            options={
                'verbose_name': '私信会话',
                'verbose_name_plural': '私信会话',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('post', 'owner', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment', '评论'), ('like', '点赞'), ('favorite', '收藏'), ('report', '举报'), ('system', '系统'), ('message', '私信')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_ignored', models.BooleanField(default=False, verbose_name='是否已忽略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interactions.conversation', verbose_name='会话')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '私信消息',
                'verbose_name_plural': '私信消息',
                'db_table': 'private_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
