# Generated by Django 6.0.3 on 2026-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('tag', models.CharField(choices=[('表白', '表白'), ('吐槽', '吐槽'), ('求助', '求助'), ('树洞', '树洞'), ('失物招领', '失物招领'), ('搭子', '搭子')], max_length=20, verbose_name='标签')),
                ('bg_color', models.IntegerField(choices=[(1, '樱花粉'), (2, '蜜桃橘'), (3, '薄荷青'), (4, '天空蓝'), (5, '薰衣紫'), (6, '柠檬黄'), (7, '云雾白'), (8, '奶茶棕')], default=7, verbose_name='背景色')),
                ('status', models.CharField(choices=[('normal', '正常'), ('ai_suspect', 'AI存疑'), ('pending', '待审核'), ('rejected', '已下架')], default='normal', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
