# Generated by Django 6.0.3 on 2026-03-25 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='post',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.anonymousidentity', verbose_name='匿名身份'),
        ),
    ]
