# Generated by Django 6.0.3 on 2026-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(max_length=500, verbose_name='正文')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='展示开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='展示结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='allow_messages',
            field=models.BooleanField(default=True, verbose_name='允许私信'),
        ),
        migrations.AddField(
            model_name='post',
            name='destroy_after_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='自毁时长(小时)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶截止时间'),
        ),
    ]
