# Generated by Django 6.0.3 on 2026-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_announcement_post_allow_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_decision',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='AI审核结论'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_reason',
            field=models.TextField(blank=True, default='', verbose_name='AI审核原因'),
        ),
    ]
