# Generated by Django 6.0.3 on 2026-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='内容')),
                ('status', models.CharField(choices=[('normal', '正常'), ('ai_suspect', 'AI存疑'), ('pending', '待审核'), ('rejected', '已下架')], default='normal', max_length=20, verbose_name='状态')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
    ]
