# Generated by Django 6.0.3 on 2026-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_ai_decision_comment_ai_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True, default='', verbose_name='审核/违规原因'),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_source',
            field=models.CharField(choices=[('none', '未触发'), ('hard_word', '硬拦截'), ('soft_word', '软标记'), ('ai', 'AI审核'), ('manual', '人工审核')], default='none', max_length=20, verbose_name='审核来源'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核截止时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='人工审核时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='risk_level',
            field=models.CharField(choices=[('none', '无'), ('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='none', max_length=10, verbose_name='风险等级'),
        ),
    ]
